apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-management-service-api
  description: API for handling orders
  owner: team-commerce
spec:
  type: openapi
  lifecycle: production
  system: ecommerce-system
  definition:
    $text: https://api.example.com/order-management-service/openapi.yaml
  owner: team-commerce
