apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-management-service
  description: Handles order lifecycle
  owner: team-commerce
spec:
  type: service
  lifecycle: production
  system: ecommerce-system
  implementsApis:
    - order-management-service-api
