apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-events
  description: Kafka topic for order events
spec:
  type: messageQueue
  owner: team-commerce
  system: ecommerce-system
