apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-processing-service
  description: Handles payments and transactions
  owner: team-commerce
spec:
  type: service
  lifecycle: production
  system: ecommerce-system
  owner: team-commerce
  implementsApis:
    - payment-processing-service-api
  dependsOn:
    - payment-db
    - payment-gateway