apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inventory-db
  description: PostgreSQL database for inventory tracking
spec:
  type: database
  owner: team-commerce
  system: ecommerce-system
