apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cart-service
  description: Manages user shopping carts
  owner: team-commerce
spec:
  type: service
  lifecycle: production
  system: ecommerce-system
  owner: team-commerce
  implementsApis:
    - cart-service-api
  dependsOn:
    - cart-redis
