apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: product-catalog-db
  description: Database storing product metadata
spec:
  type: database
  owner: team-commerce
  system: ecommerce-system
  usedBy:
    - product-catalog-service
